package:
  name: tensorflow-engram
  version: "0.1.0"

source:
  path: .

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/danielathome19/Engram-Neural-Network
  license: BSD-3-Clause
  summary: A Python package for Engram Neural Networks, adding biologically-inspired Hebbian memory and engram layers to TensorFlow/Keras models, supporting memory traces, plasticity, attention, and sparsity for neural sequence learning.