name: CI/CT/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build PyPI package
      if: success()
      run: |
        python setup.py sdist bdist_wheel

    - name: Check if version exists on PyPI
      id: pypi_version_check
      run: |
        pip install requests
        PACKAGE_NAME="tensorflow-engram"
        VERSION=$(python setup.py --version)
        response=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/project/$PACKAGE_NAME/$VERSION/)
        if [ $response -eq 200 ]; then
          echo "Version $VERSION already exists on PyPI."
          echo "::set-output name=exists::true"
        else
          echo "Version $VERSION does not exist on PyPI."
          echo "::set-output name=exists::false"
        fi

    - name: Publish to PyPI
      if: steps.pypi_version_check.outputs.exists == 'false'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install twine
        twine upload dist/* --verbose
